from time import sleep
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument("--incognito")

driver = webdriver.Chrome(options=chrome_options)
driver.get('https://buyme.co.il/')
sleep(1)
first_sign_up = driver.find_element(by='xpath', value='//*[@id="ember1006"]/div/ul[1]/li[3]/a/span')
first_sign_up.click()
sleep(1)
second_sign_up = driver.find_element(by='xpath', value='//*[@id="ember964"]/div/div[1]/div/div/div[3]/div[1]/span')
second_sign_up.click()
sleep(1)
first_name_enter = driver.find_element(by='xpath', value='//*[@id="ember1878"]')
first_name_enter.send_keys('Daniel')
sleep(1)
email_submit = driver.find_element(by='xpath', value='//*[@id="ember1885"]')
email_submit.send_keys('matantarif123@gmail.com')
sleep(1)
first_time_password = driver.find_element(by='xpath', value='//*[@id="valPass"]')
first_time_password.send_keys('Aa123456!')
sleep(1)
second_time_password = driver.find_element(by='xpath', value='//*[@id="ember1899"]')
second_time_password.send_keys('Aa123456!')
sleep(1)
agree_on_terms_button = driver.find_element(by='xpath', value='//*[@id="ember1905"]/div/span[1]')
agree_on_terms_button.click()
submit_button = driver.find_element(by='xpath', value='//*[@id="ember1909"]')
submit_button.click()
sleep(1)
submit_button = driver.find_element(by='xpath', value='//*[@id="ember1845"]')
submit_button.click()
sleep(1)
first_sign_up = driver.find_element(by='xpath', value='//*[@id="ember1006"]/div/ul[1]/li[3]/a/span')
first_sign_up.click()
sleep(1)
mail_for_sign_in = driver.find_element(by='xpath', value='//*[@id="ember1926"]')
mail_for_sign_in.send_keys('matantarif12@gmail.com')
sleep(1)
password_for_sign_in = driver.find_element(by='xpath', value='//*[@id="ember1933"]')
password_for_sign_in.send_keys('Aa123456!')
sleep(1)
enter_website_button = driver.find_element(by='xpath', value='//*[@id="ember1942"]/span')
enter_website_button.click()
sleep(10)
choose_price_roller = driver.find_element(by='xpath', value='//*[@id="ember1054"]/div/div[1]/span')
choose_price_roller.click()
sleep(1)
choose_price = driver.find_element(by='xpath', value='//*[@id="ember1076"]/span')
choose_price.click()
sleep(1)
choose_area_roller = driver.find_element(by='xpath', value='//*[@id="ember1089"]/div/div[1]/span')
choose_area_roller.click()
sleep(1)
choose_area = driver.find_element(by='xpath', value='//*[@id="ember1111"]/span')
choose_area.click()
sleep(1)
choose_category_roller = driver.find_element(by='xpath', value='//*[@id="ember1121"]/div/div[1]/span')
choose_category_roller.click()
sleep(1)
choose_category = driver.find_element(by='xpath', value='//*[@id="ember1182"]/span')
choose_category.click()
sleep(1)
click_search = driver.find_element(by='xpath', value='//*[@id="ember1200"]')
click_search.click()
sleep(2)
choose_business = driver.find_element(by='xpath', value='//*[@id="ember2174"]/div[3]/span')
choose_business.click()
sleep(1)
enter_price = driver.find_element(by='xpath', value='//*[@id="ember2342"]')
enter_price.send_keys('100')
sleep(1)
click_to_choose = driver.find_element(by='xpath', value='//*[@id="ember2348"]/span')
click_to_choose.click()
sleep(1)
choose_person = driver.find_element(by='xpath', value='//*[@id="ember2474"]')
choose_person.send_keys('My panda')
sleep(1)
choose_for_what_roller = driver.find_element(by='xpath', value='//*[@id="ember2535"]/div/div[1]/span')
choose_for_what_roller.click()
sleep(1)
choose_for_what = driver.find_element(by='xpath', value='//*[@id="ember2577"]/span')
choose_for_what.click()
sleep(1)
upload_photo = driver.find_element(by='xpath', value='//*[@id="ember2494"]')
sleep(3)
upload_photo.send_keys('C:/Users/Daniel-G/Desktop/download.jpg')
sleep(1)
continue_to_purchase = driver.find_element(by='xpath', value='//*[@id="ember2495"]/span')
continue_to_purchase.click()
sleep(2)
send_later = driver.find_element(by='xpath', value='//*[@id="ember2622"]/span')
send_later.click()
sleep(2)
pick_date_button = driver.find_element(by='xpath', value='//*[@id="ember2661"]')
pick_date_button.click()
sleep(1)
pick_date = driver.find_element(by='xpath', value='//*[@id="ember2740"]')
pick_date.click()
sleep(1)
pick_hour_roller = driver.find_element(by='xpath', value='//*[@id="ember2741"]/div/div[1]/span')
pick_hour_roller.click()
sleep(1)
pick_hour = driver.find_element(by='xpath', value='//*[@id="ember2937"]')
pick_hour.click()
sleep(1)
send_sms = driver.find_element(by='xpath', value='//*[@id="ember2627"]/div[1]/div[1]')
send_sms.click()
sleep(1)
send_sms_number = driver.find_element(by='xpath', value='//*[@id="sms"]')
send_sms_number.send_keys('0508428213')
sleep(1)
send_sms_number = driver.find_element(by='xpath', value='//*[@id="ember3176"]')
send_sms_number.send_keys('0508428213')
sleep(1)
now_pay = driver.find_element(by='xpath', value='//*[@id="ember2652"]/span')
now_pay.click()
sleep(5)
driver.delete_all_cookies()
driver.refresh()
driver.quit()
